spring:
  security:
    oauth2:
      client:
        registration:
          spotify-artist-insight-service:
            provider: spotify
            client-id: 1234e12345678fafbd90fdce7540e12e
            client-secret: 12b123b7c2ea4cf28abc83f3e12345de
            authorization-grant-type: authorization_code
            scope: user-follow-read, user-read-private
          spotify-client-credentials:
            provider: spotify
            client-id: 1234e12345678fafbd90fdce7540e12e
            client-secret: 12b123b7c2ea4cf28abc83f3e12345de
            authorization-grant-type: client_credentials
            scope: user-follow-read, user-read-private
        provider:
          spotify:
            issuer-uri: http://127.0.0.1:8100
            user-info-uri: http://127.0.0.1:8100/v1/me
            userNameAttribute: display_name
app:
  default-success-url: http://127.0.0.1:3000
  login-url: http://127.0.0.1:3000/login

spotify:
  api-base-url: http://127.0.0.1:8100/v1

logging:
  level:
    WireMock: warn