server:
  port: 9016

postgres-url: jdbc:postgresql://${POSTGRES_ADDRESS:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:artist_insight_service}

spring:
  datasource:
    url: ${postgres-url}
    username: ${POSTGRES_APP_USER:d}
    password: ${POSTGRES_APP_PASSWORD:d}
  security:
    oauth2:
      client:
        registration:
          spotify-artist-insight-service:
            provider: spotify
            client-id: ${SPOTIFY_CLIENT_ID}
            client-secret: ${SPOTIFY_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: user-follow-read, user-read-private
        provider:
          spotify:
            issuer-uri: https://accounts.spotify.com
            user-info-uri: https://api.spotify.com/v1/me
            userNameAttribute: display_name

openai:
  api-key: ${OPENAI_API_KEY}


#logging:
#  level:
#    root: DEBUG