spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

  flyway:
    locations:
      - filesystem:templates/docker/flyway/sql/tables
