services:
  frontend:
    image: generaltao725/artist-insight-frontend:latest
    env_file:
      - ../.env
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:3000/api/actuator/health"]
      interval: 10s
      timeout: 10s
      retries: 30